
language: python
sudo: required
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6

os: "ubuntu"
# whitelist

 
# Use this to prepare the system to install prerequisites or dependencies


# command to install dependencies
install: 


- "pip install git+https://github.com/yutiansut/pytdx"
- "pip install -r requirements.txt"
- "pip install git+https://github.com/yutiansut/tushare"
# command to build
script: 


 - "python setup.py install"


