version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
        - TZ=Asia/Shanghai
        - MONGO_INITDB_DATABASE=quantaxis
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
#--
  quantaxis:
    build: qa
    image: quantaxis:latest
    container_name: quantaxis
    environment:
        - TZ=Asia/Shanghai
        - MONGODB=mongo
    volumes:
      - ./_data_:/data
      - ./_notebooks_:/home
    ports:
      - 8010:8888
      - 8888:8888
    depends_on:
        - mongo
    links:
        - mongo
